# Generated by Django 4.2.1 on 2023-05-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='to_domodel',
            options={'ordering': ('startDate', '-endDate'), 'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
        migrations.AddField(
            model_name='to_domodel',
            name='description',
            field=models.CharField(max_length=1000, null=True, verbose_name='Descricao'),
        ),
    ]
